const API = ''
let pendingFiles = []
function renderSelectedFiles(){ const listEl=document.getElementById('fileList'); if(!listEl) return; listEl.innerHTML = pendingFiles.map((f,i)=>`<div class="row" style="justify-content:space-between"><span>${f.name} · ${Math.round(f.size/1024/1024*10)/10}MB</span><button class="btn" data-remove="${i}">删除</button></div>`).join(''); Array.from(listEl.querySelectorAll('button[data-remove]')).forEach(btn=>{ btn.onclick=()=>{ const idx=Number(btn.getAttribute('data-remove')); if(!Number.isNaN(idx)){ pendingFiles.splice(idx,1); renderSelectedFiles() } } }) }
function authHeader() { const t = localStorage.getItem('token'); return t ? { Authorization: `Bearer ${t}` } : {} }
async function j(method, path, body) { const res = await fetch(API+path, { method, headers: { 'Content-Type': 'application/json', ...authHeader() }, body: body ? JSON.stringify(body) : undefined }); let data=null; try{ data=await res.json() }catch(_){} if(res.status===401){ localStorage.removeItem('token'); localStorage.removeItem('user'); location.hash='#login'; throw new Error((data&&data.detail)||'Unauthorized') } if (!res.ok) throw new Error((data&&data.detail)||String(res.status)); return data }
async function f(path, fd) { const res = await fetch(API+path, { method:'POST', headers: { ...authHeader() }, body: fd }); if (!res.ok) throw new Error(res.status); return res.json() }
const api = { register:(u,p)=>j('POST','/auth/register',{username:u,password:p}), login:(u,p)=>j('POST','/auth/login',{username:u,password:p}), me:()=>fetch(API+'/auth/me',{ headers: authHeader() }).then(r=>r.json()), listModels:(q,tags,sort)=>{ const qs=[]; if(q) qs.push(`query=${encodeURIComponent(q)}`); if(tags) qs.push(`tags=${encodeURIComponent(tags)}`); if(sort) qs.push(`sort=${encodeURIComponent(sort)}`); const url = '/models'+(qs.length?`?${qs.join('&')}`:''); return fetch(API+url).then(r=>r.json()) }, createModel:(p)=>j('POST','/models',p), getModel:(id)=>fetch(API+`/models/${id}`).then(r=>r.json()), listModelFiles:(id)=>fetch(API+`/models/${id}/files`).then(r=>r.json()), uploadModelFile:(id,file)=>{ const fd=new FormData(); fd.append('f',file); return f(`/models/${id}/upload`,fd) }, downloadUrl:(fid)=>API+`/files/${fid}/download`, health:()=>fetch(API+'/system/health').then(r=>r.json()) }
const app = document.getElementById('app'); function mount(html){ const w=document.createElement('div'); w.className='fade-enter'; w.innerHTML=html; app.innerHTML=''; app.appendChild(w); requestAnimationFrame(()=> w.className='fade-enter-active') }
function renderNav(){ const brand=document.getElementById('navBrand'); const nav=document.getElementById('nav'); const token=localStorage.getItem('token'); const user=localStorage.getItem('user')?JSON.parse(localStorage.getItem('user')):null; brand.onclick=()=>{ location.hash='#models' }; document.getElementById('navModels').onclick=()=>{ location.hash='#models' }; document.getElementById('navNew').onclick=()=>{ location.hash='#new' }; document.getElementById('navMe').onclick=()=>{ location.hash='#me' }; document.getElementById('navStats').onclick=()=>{ location.hash='#stats' }; document.getElementById('navAdmin').onclick=()=>{ location.hash='#admin' }; const traff=document.getElementById('navTraffic'); if(traff) traff.onclick=()=>{ location.hash='#traffic' }; const isAdmin = user && user.role==='admin'; document.getElementById('navAdmin').style.display = isAdmin ? 'inline-block' : 'none'; if(traff) traff.style.display = isAdmin ? 'inline-block' : 'none'; const showNav = !!token; nav.style.display = showNav ? 'flex' : 'none'; const ids=['navModels','navNew','navMe','navStats','navAdmin','navTraffic']; ids.forEach(id=>{ const el=document.getElementById(id); if(el) el.classList.remove('active') }); let target=null; const h=location.hash||'#models'; if(h==='#models' || h.startsWith('#model-')) target='navModels'; else if(h==='#new') target='navNew'; else if(h==='#me') target='navMe'; else if(h==='#stats') target='navStats'; else if(h==='#admin') target='navAdmin'; else if(h==='#traffic') target='navTraffic'; if(target){ const el=document.getElementById(target); if(el) el.classList.add('active') } }
function renderUserStatus(){ const box=document.getElementById('userStatus'); if(!box) return; const token=localStorage.getItem('token'); const user=localStorage.getItem('user')?JSON.parse(localStorage.getItem('user')):null; if(token && user){ box.innerHTML = `<span class='muted'>${user.username}</span><button id='logoutBtnTop' class='btn'>退出</button>`; const lo=document.getElementById('logoutBtnTop'); if(lo) lo.onclick=()=>{ localStorage.removeItem('token'); localStorage.removeItem('user'); location.hash='#login' } } else { box.innerHTML = `<button id='loginBtnTop' class='btn'>登录</button>`; const btn=document.getElementById('loginBtnTop'); if(btn) btn.onclick=()=>{ location.hash='#login' } } }
function viewLogin(){ mount(`<div class="container"><div class="card"><h3>登录 / 注册</h3><div class="grid" style="grid-template-columns: 1fr 1fr"><div class="grid"><label>用户ID</label><input id="username" placeholder="用户ID" /></div><div class="grid"><label>密码</label><input id="password" type="password" placeholder="密码" /></div></div><div class="row"><button id="loginBtn" class="btn primary">登录</button><button id="regBtn" class="btn">注册并登录</button><div id="err" class="muted"></div></div></div></div>`); const u=document.getElementById('username'), p=document.getElementById('password'), err=document.getElementById('err'); function validate(){ if(!u.value || !p.value || p.value.length<6){ err.textContent='账号或密码错误'; return false } err.textContent=''; return true } document.getElementById('loginBtn').onclick=async()=>{ if(!validate()) return; try{ const t=await api.login(u.value,p.value); localStorage.setItem('token',t.access_token); const me=await api.me(); localStorage.setItem('user',JSON.stringify(me)); location.hash = (me.role==='admin') ? '#admin' : '#models' }catch(e){ err.textContent='账号或密码错误' } }; document.getElementById('regBtn').onclick=async()=>{ if(!validate()) return; try{ await api.register(u.value,p.value); const t=await api.login(u.value,p.value); localStorage.setItem('token',t.access_token); const me=await api.me(); localStorage.setItem('user',JSON.stringify(me)); location.hash = (me.role==='admin') ? '#admin' : '#models' }catch(e){ err.textContent='账号或密码错误' } } }
async function viewBrowse(){ const last=JSON.parse(localStorage.getItem('browse')||'{}'); const q=last.q||''; const tg=last.tags||''; const st=last.sort||'updated_at'; const list=await api.listModels(q,tg,st); mount(`<div class="container"><div class="card"><h3>模型浏览与检索</h3><div class="grid" style="grid-template-columns: 1fr 1fr 160px"><input id="q" placeholder="标识" value="${q}" /><input id="tags" placeholder="标签（逗号分隔）" value="${tg}" /><select id="sort"><option value="updated_at" ${st==='updated_at'?'selected':''}>按更新时间</option><option value="downloads" ${st==='downloads'?'selected':''}>按下载量</option></select></div><div class="row"><button id="search" class="btn primary">搜索</button></div></div><div class="grid">${list.map(m=>`<div class='list-item'><div class='row' style='justify-content:space-between'><strong>${m.name}</strong><span class='muted'>下载 ${m.download_count||0}</span></div><div class='muted'>标识：${m.slug}</div><div class='muted'>标签：${m.tags||''}</div><div class='row'><button class='btn' onclick="location.hash='#model-${m.id}'">详情</button></div></div>`).join('') || `<div class='card'><div class='row'><span class='muted'>暂无模型</span></div></div>`}</div></div>`); document.getElementById('search').onclick=()=>{ const nq=document.getElementById('q').value; const nt=document.getElementById('tags').value; const ns=document.getElementById('sort').value; localStorage.setItem('browse',JSON.stringify({ q:nq, tags:nt, sort:ns })); viewBrowse() } }

async function viewCreate(){ const models=await api.listModels(); const lastId=Number(localStorage.getItem('new_last_model_id')||'0'); const lastName=localStorage.getItem('new_last_model_name')||''; const options=models.map(m=>`<option value="${m.id}" ${m.id===lastId?'selected':''}>${m.name}</option>`).join(''); const uploadDisabled = false; const uploadCard = `<div class="row"><input type="file" id="fileCreate" multiple style="display:none" /><button id="pickFiles" class="btn">选择文件</button><button id="createUpload" class="btn primary" ${uploadDisabled?'disabled':''}>创建并上传</button><button id="backBtn" class="btn">返回列表</button></div><div id="fileList" class="muted" style="margin-top:8px; white-space:pre-line"></div><div class="progress" style="margin-top:8px"><div id="createBar" class="progress-bar"></div></div><div id="createMsg" class="muted" style="margin-top:8px"></div>`;
  mount(`<div class="container"><div class="card"><h3>新建模型</h3><div class="grid" style="grid-template-columns: 1fr 1fr"><input id="name" placeholder="名称" /><input id="slug" placeholder="标识（slug）" /><input id="tags" placeholder="标签（逗号分隔）" /><input id="desc" placeholder="简介" /></div><div class="row"><div id="err" class="muted"></div></div></div>${uploadCard}</div>`);
  const fe=document.getElementById('fileCreate'); const fl=document.getElementById('fileList'); const pick=document.getElementById('pickFiles'); if(pick && fe){ pick.onclick=()=> fe.click() } if(fe){ fe.addEventListener('change', ()=>{ const arr=(fe && fe.files)? Array.from(fe.files):[]; for(const f of arr){ if(!pendingFiles.some(x=> x.name===f.name && x.size===f.size && x.lastModified===f.lastModified)){ pendingFiles.push(f) } } fe.value=''; renderSelectedFiles(); const bar=document.getElementById('createBar'); if(bar) bar.style.width='0%' }) }
const createBtn=document.getElementById('create'); if(createBtn) createBtn.onclick=async()=>{ const name=document.getElementById('name').value; const slug=document.getElementById('slug').value; const err=document.getElementById('err'); if(!name||!slug){ err.textContent='请填写名称和标识'; return } const payload={ name, slug, description:document.getElementById('desc').value, tags:document.getElementById('tags').value }; try{ const m=await api.createModel(payload); localStorage.setItem('new_last_model_id', String(m.id)); localStorage.setItem('new_last_model_name', m.name); viewCreate() }catch(e){ err.textContent = e.message || '创建失败' } };
  const btn=document.getElementById('createUpload'); if(btn){ btn.onclick=async()=>{ const msg=document.getElementById('createMsg'); const bar=document.getElementById('createBar'); const names=document.getElementById('fileNames'); const files=pendingFiles.slice(); if(!files.length){ msg.textContent='请选择文件'; return } const name=document.getElementById('name').value; const slug=document.getElementById('slug').value; const err=document.getElementById('err'); if(!name||!slug){ err.textContent='请填写名称和标识'; return } const payload={ name, slug, description:document.getElementById('desc').value, tags:document.getElementById('tags').value }; try{ const m=await api.createModel(payload); for(let i=0;i<files.length;i++){ const file=files[i]; await new Promise((resolve,reject)=>{ const xhr=new XMLHttpRequest(); xhr.open('POST', `/models/${m.id}/upload`); const h=authHeader(); Object.entries(h).forEach(([k,vv])=> xhr.setRequestHeader(k,vv)); xhr.upload.onprogress=e=>{ if(e.lengthComputable){ const pct=Math.round(e.loaded/e.total*100); bar.style.width=pct+'%' } }; xhr.onload=()=> xhr.status>=200 && xhr.status<300 ? resolve(xhr.responseText) : reject(new Error(xhr.status)); xhr.onerror=()=> reject(new Error('network')); const fd=new FormData(); fd.append('f', file); xhr.send(fd) }); msg.textContent=`已上传 ${i+1}/${files.length}` } pendingFiles=[]; if(names) names.textContent=''; const fe2=document.getElementById('fileCreate'); if(fe2) fe2.value=''; location.hash=`#model-${m.id}` }catch(e){ msg.textContent = (e && e.message) ? '上传失败：'+e.message : '上传失败' } } }
}
async function viewModel(id){ const m=await api.getModel(id); const files=await api.listModelFiles(id); mount(`<div class="container"><div class="row"><button class="btn" onclick="location.hash='#models'">返回列表</button><button class="btn" onclick="location.hash='#new'">新建模型</button></div><div class="card"><h2>${m.name}</h2><div class="muted">${m.description||''}</div><div class="muted">标识：${m.slug}</div><div class="muted">标签：${m.tags||''}</div></div><div class="card"><h3>文件清单</h3><div class="grid" id="filesBox"></div></div></div>`); const box=document.getElementById('filesBox'); box.innerHTML=files.map(f=>`<div class='row' style='justify-content:space-between'><span>${f.filename} · ${Math.round(f.size/1024/1024*10)/10}MB</span><a class='btn' href='${api.downloadUrl(f.id)}' target='_blank'>下载</a></div>`).join('') }
// 已收敛到单模型单文件，移除旧版本相关操作
async function viewMe(){ const me=localStorage.getItem('user')?JSON.parse(localStorage.getItem('user')):await api.me(); if(!localStorage.getItem('user')) localStorage.setItem('user',JSON.stringify(me)); const all=await api.listModels(); const mine=all.filter(m=>m.owner_id===me.id); let files=0, size=0; for(const m of mine){ const fls=await api.listModelFiles(m.id); files+=fls.length; for(const f of fls){ size+=f.size } } const toMB=Math.round(size/1024/1024*10)/10; mount(`<div class="container"><div class="row"><div class="card"><div class="row"><strong>我的模型</strong><span>${mine.length}</span></div></div><div class="card"><div class="row"><strong>文件数</strong><span>${files}</span></div></div><div class="card"><div class="row"><strong>占用存储</strong><span>${toMB} MB</span></div></div></div><div class="grid">${mine.map(m=>`<div class='list-item'><div class='row' style='align-items:center'><strong style='flex:1'>${m.name}</strong><span class='muted' style='width:90px;text-align:right'>下载 ${m.download_count||0}</span></div><div class='muted'>${m.description||''}</div><div class='row'><button class='btn' onclick="location.hash='#model-${m.id}'">详情</button></div></div>`).join('')||`<div class='card'><div class='row'><span class='muted'>暂无模型</span><button class='btn primary' onclick="location.hash='#new'">去创建模型</button></div></div>`}</div></div>`) }

async function viewStats(){ const all=await api.listModels(); let size=0; for(const m of all){ const fls=await api.listModelFiles(m.id); for(const f of fls){ size+=f.size } } const totalDownloads=all.reduce((a,b)=>a+(b.download_count||0),0); const toMB=Math.round(size/1024/1024*10)/10; const hot=all.slice().sort((a,b)=> (b.download_count||0)-(a.download_count||0)).slice(0,10); mount(`<div class="container"><div class="row"><div class="card"><div class="row"><strong>总模型数</strong><span>${all.length}</span></div></div><div class="card"><div class="row"><strong>总下载量</strong><span>${totalDownloads}</span></div></div><div class="card"><div class="row"><strong>仓库大小</strong><span>${toMB} MB</span></div></div></div><div class="card"><div class="row"><strong>热门模型榜</strong><select id='range'><option value='7'>近7天</option><option value='30'>近30天</option></select><span class='muted'>尚未支持按时间统计</span></div><div class="grid">${hot.map(m=>`<div class='row' style='align-items:center'><span style='flex:1'>${m.name}</span><span class='muted' style='width:90px;text-align:right'>下载 ${m.download_count||0}</span><button class='btn' style='width:64px' onclick="location.hash='#model-${m.id}'">详情</button></div>`).join('')}</div></div></div>`) }

async function viewAdmin(){ const me=localStorage.getItem('user')?JSON.parse(localStorage.getItem('user')):await api.me(); if(me.role!=='admin'){ location.hash='#login'; return } const health=await api.health(); const all=await api.listModels(); mount(`<div class="container"><div class="card"><div class="row"><strong>系统状态</strong><span class='muted'>数据库：${health.db}</span><span class='muted'>存储路径：${health.storage_dir}</span></div></div><div class="card"><h3>管理</h3><div class='grid'>${all.map(m=>`<div class='row' style='justify-content:space-between'><span>${m.name} · <span class='muted'>${m.slug}</span></span><div class='row'><button class='btn danger' data-del='${m.id}'>删除模型</button></div></div>`).join('')}</div></div></div>`); Array.from(document.querySelectorAll("button[data-del]")).forEach(btn=>{ btn.onclick=async()=>{ const id=Number(btn.getAttribute('data-del')); if(!id) return; try{ await j('DELETE', `/models/${id}`); viewAdmin() }catch(e){ alert('删除失败') } } }) }

function enhanceCreateUI(){ if(location.hash!=='#new') return; const card=document.querySelector('.container .card'); if(!card) return; if(document.getElementById('createUpload')) return; const row=document.createElement('div'); row.className='row'; row.innerHTML=`<input type='file' id='fileCreate' /><button id='createUpload' class='btn primary'>创建并上传</button>`; card.appendChild(row); const prog=document.createElement('div'); prog.className='progress'; prog.style.marginTop='8px'; prog.innerHTML=`<div id='createBar' class='progress-bar'></div>`; card.appendChild(prog); const msg=document.createElement('div'); msg.id='createMsg'; msg.className='muted'; msg.style.marginTop='8px'; card.appendChild(msg); const btn=document.getElementById('createUpload'); btn.onclick=async()=>{ const name=document.getElementById('name').value; const slug=document.getElementById('slug').value; const err=document.getElementById('err'); const bar=document.getElementById('createBar'); const fileEl=document.getElementById('fileCreate'); const file=fileEl && fileEl.files && fileEl.files[0]; const msgEl=document.getElementById('createMsg'); if(!name||!slug){ err.textContent='请填写名称和标识'; return } if(!file){ msgEl.textContent='请选择文件'; return } const payload={ name, slug, description:document.getElementById('desc').value, tags:document.getElementById('tags').value }; try{ const m=await api.createModel(payload); await new Promise((resolve,reject)=>{ const xhr=new XMLHttpRequest(); xhr.open('POST', `/models/${m.id}/upload`); const h=authHeader(); Object.entries(h).forEach(([k,vv])=> xhr.setRequestHeader(k,vv)); xhr.upload.onprogress=e=>{ if(e.lengthComputable){ const pct=Math.round(e.loaded/e.total*100); bar.style.width=pct+'%' } }; xhr.onload=()=> xhr.status>=200 && xhr.status<300 ? resolve(xhr.responseText) : reject(new Error(xhr.status)); xhr.onerror=()=> reject(new Error('network')); const fd=new FormData(); fd.append('f', file); xhr.send(fd) }); location.hash=`#model-${m.id}` }catch(e){ msgEl.textContent='创建或上传失败' } } }

function router(){ renderNav(); const t=localStorage.getItem('token'); const h=location.hash||'#models'; if(!t && h!=='#login'){ return viewLogin() } if(h==='#login') return viewLogin(); if(h==='#models') return viewBrowse(); if(h==='#new') { viewCreate(); enhanceCreateUINew(); return } if(h==='#me') return viewMe(); if(h==='#stats') return viewStats(); if(h.startsWith('#model-')) return viewModel(Number(h.replace('#model-',''))); if(h==='#admin') return viewAdmin(); if(h==='#traffic') return viewTraffic(); return viewBrowse() }
window.addEventListener('hashchange', ()=>{ router(); enhanceCreateUINew(); renderUserStatus() }); router(); enhanceCreateUINew(); renderUserStatus()

function enhanceCreateUINew(){
  if(location.hash!=='#new') return;
  const card=document.querySelector('.container .card');
  if(!card) return;
  const existed=document.getElementById('createUpload');
  if(!existed){
    const row=document.createElement('div');
    row.className='row';
    row.innerHTML=`<input type='file' id='fileCreate' multiple style='display:none' /><button id='pickFiles' class='btn'>选择文件</button><button id='createUpload' class='btn primary'>创建并上传</button><button id='backBtn' class='btn'>返回列表</button>`;
    card.appendChild(row);
    const prog=document.createElement('div');
    prog.className='progress';
    prog.style.marginTop='8px';
    prog.innerHTML=`<div id='createBar' class='progress-bar'></div>`;
    card.appendChild(prog);
    const msg=document.createElement('div');
    msg.id='createMsg';
    msg.className='muted';
    msg.style.marginTop='8px';
    card.appendChild(msg);
    const list=document.createElement('div');
    list.id='fileList';
    list.className='muted';
    list.style.marginTop='8px';
    list.style.whiteSpace='pre-line';
    card.appendChild(list);
  }
  const fileEl=document.getElementById('fileCreate');
  const pickBtn=document.getElementById('pickFiles');
  if(pickBtn && fileEl){ pickBtn.onclick=()=> fileEl.click() }
  if(fileEl){
    try{ fileEl.style.minWidth='auto'; fileEl.style.width='180px'; }catch(e){}
    fileEl.addEventListener('change', ()=>{
      const arr=(fileEl && fileEl.files) ? Array.from(fileEl.files) : [];
      for(const f of arr){ if(!pendingFiles.some(x=> x.name===f.name && x.size===f.size && x.lastModified===f.lastModified)){ pendingFiles.push(f) } }
      fileEl.value='';
      const names=pendingFiles.map(f=> `${f.name} · ${Math.round(f.size/1024/1024*10)/10}MB`);
      const fn=document.getElementById('fileNames'); if(fn) fn.textContent = names.length ? names.join('；') : '';
      const fl=document.getElementById('fileList'); if(fl) fl.textContent = names.length ? names.join('\n') : '';
      const bar=document.getElementById('createBar'); if(bar) bar.style.width='0%';
    });
  }
  const btn=document.getElementById('createUpload');
  btn.onclick=async()=>{
    const name=document.getElementById('name').value;
    const slug=document.getElementById('slug').value;
    const err=document.getElementById('err');
    const bar=document.getElementById('createBar');
    const files=pendingFiles.slice();
    const msgEl=document.getElementById('createMsg');
    if(!name||!slug){ err.textContent='请填写名称和标识'; return }
    if(!files.length){ msgEl.textContent='请选择文件'; return }
    const payload={ name, slug, description:document.getElementById('desc').value, tags:document.getElementById('tags').value };
    try{
      const m=await api.createModel(payload);
      for(let i=0;i<files.length;i++){
        const file=files[i];
        await new Promise((resolve,reject)=>{
          const xhr=new XMLHttpRequest();
          xhr.open('POST', `/models/${m.id}/upload`);
          const h=authHeader(); Object.entries(h).forEach(([k,vv])=> xhr.setRequestHeader(k,vv));
          xhr.upload.onprogress=e=>{ if(e.lengthComputable){ const pct=Math.round(e.loaded/e.total*100); bar.style.width=pct+'%' } };
          xhr.onload=()=> xhr.status>=200 && xhr.status<300 ? resolve(xhr.responseText) : reject(new Error(xhr.status));
          xhr.onerror=()=> reject(new Error('network'));
          const fd=new FormData(); fd.append('f', file); xhr.send(fd);
        });
        msgEl.textContent=`已上传 ${i+1}/${files.length}`;
      }
      pendingFiles=[];
      location.hash=`#model-${m.id}`;
    }catch(e){ msgEl.textContent = (e && e.message) ? '上传失败：'+e.message : '上传失败' }
  }
  const back=document.getElementById('backBtn'); if(back){ back.onclick=()=>{ location.hash='#models' } }
}
async function viewTraffic(){ const me=localStorage.getItem('user')?JSON.parse(localStorage.getItem('user')):await api.me(); if(me.role!=='admin'){ location.hash='#login'; return } function render(data){ const list=(data.active||[]).map(x=>`<div class='list-item'><div class='row' style='justify-content:space-between'><span>${x.filename}</span><span class='muted'>${Math.round((x.bytes||0)/1024/1024*10)/10}MB / ${Math.round((x.total||0)/1024/1024*10)/10}MB</span></div><div class='progress'><div class='progress-bar' style='width:${x.percent||0}%'></div></div></div>`).join(''); mount(`<div class='container'><div class='card'><div class='row'><strong>流量监控</strong><span class='muted'>并发目标：5</span></div></div><div class='grid'>${list || `<div class='card'><span class='muted'>暂无活动下载</span></div>`}</div></div>`); } async function load(){ try{ const d=await fetch('/system/traffic', { headers: authHeader() }).then(r=>r.json()); render(d) }catch(e){ render({active:[]}) } } await load(); if(window.__trafTimer) clearInterval(window.__trafTimer); window.__trafTimer=setInterval(load, 1000) }
